export enum AuthExceptionCodes {
  AUTHORIZATION_HEADER_MISSING = "AUTHORIZATION_HEADER_MISSING",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  INVALID_TOKEN_FORMAT = "INVALID_TOKEN_FORMAT",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  USER_ALREADY_CONFIRMED_EMAIL = "USER_ALREADY_CONFIRMED_EMAIL",
  WRONG_PASSWORD = "WRONG_PASSWORD",
}
