export enum SubscriptionExceptionCodes {
  SUBSCRIPTION_NOT_FOUND = "SUBSCRIPTION_NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  PLAN_NOT_FOUND = "PLAN_NOT_FOUND",
  CHECKOUT_SESSION_NOT_CREATED = "CHECKOUT_SESSION_NOT_CREATED",
  CHECKOUT_SESSION_NOT_FOUND = "CHECKOUT_SESSION_NOT_FOUND",
  USER_ALREADY_SUBSCRIBED = "USER_ALREADY_SUBSCRIBED",
  UNKNOWN_SUBSCRIPTION_STATUS = "UNKNOWN_SUBSCRIPTION_STATUS",
  
}