export enum ModuleType {
  PAYMENT_MODULE = "PaymentModule",
  EMAIL_MODULE = "EmailModule",
  USER_MODULE = "UserModule",
  SUBSCRIPTION_MODULE = "SubscriptionModule",
  ROLES_MODULE = "RolesModule",
  AUTH_MODULE = "AuthModule",
  ACTION_TOKEN_MODULE = "ActionTokenModule",
  STRIPE_MODULE = "StripeModule",
  TOKEN_MODULE = "Common/Auth/TokenModule",
  PASSWORD_MODULE = "Common/Auth/PasswordModule",
  PRODUCT_MODULE = "ProductModule",
  PLAN_MODULE = "PlanModule",
  PADDLE_MODULE = "PaddleModule",
  DRAFT_PLAN_MODULE = "DraftPlanModule",
  USER_PREDICTION_MODULE = "UserPredictionModule",
  TIER_MODULE = "TierModule",
  PREDICTION_MODULE = "PredictionModule",
}
