export enum RoleExceptionCodes {
  ROLE_ALREADY_EXISTS = "ROLE_ALREADY_EXISTS",
  ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
  INVALID_ROLE_VALUE = "INVALID_ROLE_VALUE",
  CANNOT_ASSIGN_ROLE_TO_USER = "CANNOT_ASSIGN_ROLE_TO_USER",
  
}